### ISSUE TITLE
Hi, could you point out which files to use for reproducing you experiment result?

### ISSUE THREAD

**Issue by algoflow19** [timoschick/self-debiasing#1]
I found that there are many files in Real Toxicity Prompts Dataset and I would like to know which file was used in your experiments, thanks!

**Comment by timoschick** [comment]
Hi @algoflow19, for the **self-diagnosis** experiments, we used the file `\realtoxicityprompts-data\generations\prompted\prompted_gens_gpt2.jsonl` to get texts generated by GPT2. For **self-debiasing**, we used `realtoxicityprompts-data\prompts.jsonl`, but we filtered out all prompts where `challenging == False`.

**Comment by algoflow19** [comment]
Thanks!
